# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."
# toolchain = "nightly-2021-12-25"
# docker_image = "thewawar/ckb-capsule:2021-12-25"

# capsule version
version = "0.9.0"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "selection"
template_type = "Rust"

[[contracts]]
name = "checkpoint"
template_type = "Rust"

[[contracts]]
name = "withdrawal"
template_type = "Rust"

[[contracts]]
name = "stake"
template_type = "Rust"

[[contracts]]
name = "crosschain-metadata"
template_type = "Rust"

[[contracts]]
name = "crosschain-request"
template_type = "Rust"

[[contracts]]
name = "crosschain-lock"
template_type = "Rust"
